version: '3.8'

services:
  home-assistant:
    container_name: homeassistant
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
#      - /PATH_TO_YOUR_CONFIG:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host
    image: ghcr.io/home-assistant/home-assistant:stable
